const stopwords = {
    'about': true,
    'after': true,
    'all': true,
    'also': true,
    'am': true,
    'an': true,
    'and': true,
    'another': true,
    'any': true,
    'are': true,
    'as': true,
    'at': true,
    'be': true,
    'because': true,
    'been': true,
    'before': true,
    'being': true,
    'between': true,
    'both': true,
    'but': true,
    'by': true,
    'came': true,
    'can': true,

    'come': true,
    'could': true,
    'did': true,
    'do': true,
    'each': true,
    'for': true,
    'from': true,
    'get': true,
    'got': true,
    'has': true,
    'had': true,

    'he': true,
    'have': true,
    'her': true,
    'here': true,
    'him': true,
    'himself': true,
    'his': true,
    'how': true,
    'if': true,
    'in': true,
    'into': true,

    'is': true,
    'it': true,
    'like': true,
    'make': true,
    'many': true,
    'me': true,
    'might': true,
    'more': true,
    'most': true,
    'much': true,
    'must': true,

    'my': true,
    'never': true,
    'now': true,
    'of': true,
    'on': true,
    'only': true,
    'or': true,
    'other': true,
    'our': true,
    'out': true,
    'over': true,

    'said': true,
    'same': true,
    'see': true,
    'should': true,
    'since': true,
    'some': true,
    'still': true,
    'such': true,
    'take': true,
    'than': true,

    'that': true,
    'the': true,
    'their': true,
    'them': true,
    'then': true,
    'there': true,
    'these': true,
    'they': true,
    'this': true,
    'those': true,

    'through': true,
    'to': true,
    'too': true,
    'under': true,
    'up': true,
    'very': true,
    'was': true,
    'way': true,
    'we': true,
    'well': true,
    'were': true,

    'what': true,
    'where': true,
    'which': true,
    'while': true,
    'who': true,
    'with': true,
    'would': true,
    'you': true,
    'your': true,
    'a': true,
    'i': true,

    'rt': true,
    'amp': true,
    '': true,
    'not': true,
    'trump': true,
    'trumps': true,
    'will': true,
    'not': true,
    'president': true,
    'its': true,
    'donald': true,

    'trump': true,
    'donaldtrump': true,
    'http': true,
    'https': true,
    'realdonaldtrump': true,
    'when': true,
    'know': true,
    'lets': true,
    'just': true,
    'dont': true,

    'potus': true,
    'realdonaldtrump': true,
    'realdonaldtrumps': true
}

module.exports = stopwords;